// <auto-generated />
namespace Sem3_backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class touristDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(touristDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202011270616105_touristDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
